### ISSUE TITLE
Project Code + Senstive data

### ISSUE THREAD

**Issue by ZaidKindman** [Health-360-AI/Clinic360-Online#1]
# Revert Commit 🔴
The last commit "deleted" can be reverted, therfore project code can be seen by anyone.
I don't know if this was intended and the project meant to be an open-source project or a learning-project.
**just telling you for good intentions 😊**

# Sensitve data ⚠️
Some of the data written in these files could be senstive data:
* **notarizeDMG.js** 
* **env.js** 

### Make the project private if these are big issues 😊

**Comment by Sajad321** [comment]
Thank you for noticing that, it was very helpful, and we fixed it.
